package tech.soulcoder.dao.generator;

import tech.soulcoder.pojo.generator.SoulUser;

public interface SoulUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table soul_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table soul_user
     *
     * @mbg.generated
     */
    int insert(SoulUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table soul_user
     *
     * @mbg.generated
     */
    int insertSelective(SoulUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table soul_user
     *
     * @mbg.generated
     */
    SoulUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table soul_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SoulUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table soul_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SoulUser record);
}